### ISSUE TITLE
The following error occurred while making my own dataset

### ISSUE THREAD

**Issue by bukeyan4318** [dlinzhao/JSNet#12]
hello，
The following error occurred while making my own dataset：
**Traceback (most recent call last):
  File "utils/s3dis_utils/s3dis_gen_h5.py", line 36, in <module>
    random_sample=False, sample_num=None)
  File "/shiyanshi2/user/sunyijun/code/JSNet-master-kiwifruit/utils/indoor3d_util.py", line 372, in room2blocks_wrapper_normalized
    random_sample, sample_num, sample_aug)
  File "/shiyanshi2/user/sunyijun/code/JSNet-master-kiwifruit/utils/indoor3d_util.py", line 343, in room2blocks_plus_normalized
    random_sample, sample_num, sample_aug)
  File "/shiyanshi2/user/sunyijun/code/JSNet-master-kiwifruit/utils/indoor3d_util.py", line 296, in room2blocks
    return np.concatenate(block_data_list, 0), \
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate**
Can you help me see what's wrong?

**Comment by dlinzhao** [comment]
@bukeyan4318 you can test the function `room2blocks_wrapper_normalized` to check whether the data is being read correctly.
