### ISSUE TITLE
Use my own dataset to train errors

### ISSUE THREAD

**Issue by bukeyan4318** [dlinzhao/JSNet#13]
Traceback (most recent call last):
  File "train.py", line 226, in <module>
    train()
  File "train.py", line 183, in train
    train_one_epoch(sess, ops, train_writer, dataset, epoch)
  File "train.py", line 222, in train_one_epoch
    logger.info('mean loss: %f' % (loss_sum / float(num_batches)))
ZeroDivisionError: float division by zero
Exception ignored in: <bound method S3DISDataset.__del__ of <s3dis_utils.dataset_s3dis.S3DISDataset object at 0x7f6acd354ac8>>
Traceback (most recent call last):
  File "/shiyanshi2/user/sunyijun/code/JSNet-master-kiwifruit/utils/s3dis_utils/dataset_s3dis.py", line 151, in __del__
    while not self.data_sample_queue.empty() and not self.data_queue.empty():
  File "<string>", line 2, in empty
  File "/shiyanshi2/software/anaconda3/envs/JSNet/lib/python3.5/multiprocessing/managers.py", line 713, in _callmethod
    self._connect()
  File "/shiyanshi2/software/anaconda3/envs/JSNet/lib/python3.5/multiprocessing/managers.py", line 700, in _connect
    conn = self._Client(self._token.address, authkey=self._authkey)
  File "/shiyanshi2/software/anaconda3/envs/JSNet/lib/python3.5/multiprocessing/connection.py", line 487, in Client
    c = SocketClient(address)
  File "/shiyanshi2/software/anaconda3/envs/JSNet/lib/python3.5/multiprocessing/connection.py", line 614, in SocketClient
    s.connect(address)
FileNotFoundError: [Errno 2] No such file or directory

What's wrong? We look forward to your reply

**Comment by dlinzhao** [comment]
@bukeyan4318 It seems that the dataset was not loaded correctly. Firstly, you can test the Dataset class by using a simple script.
