### ISSUE TITLE
ValueError: need at least one array to concatenate

### ISSUE THREAD

**Issue by PengboLi1998** [dlinzhao/JSNet#19]
When I use my own dataset,it throws error as following,i am sure my dataset path is correct,but it still .Could you please help me?

E:\Anaconda3\envs\lpb\python.exe D:/ASIS-master/gen_h5.py
D:\ASIS-master\data\indoor3d_ins_seg_hdf5\Area_1_hallway_1.h5: (3, 4096, 9), (3, 4096), (3, 4096)
D:\ASIS-master\utils\data_prep_util.py:95: H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
  h5_fout = h5py.File(h5_filename)
Traceback (most recent call last):
  File "D:/ASIS-master/gen_h5.py", line 37, in <module>
    random_sample=False, sample_num=None)
  File "D:\ASIS-master\indoor3d_util.py", line 281, in room2blocks_wrapper_normalized
    random_sample, sample_num, sample_aug)
  File "D:\ASIS-master\indoor3d_util.py", line 257, in room2blocks_plus_normalized
    random_sample, sample_num, sample_aug)
  File "D:\ASIS-master\indoor3d_util.py", line 215, in room2blocks
    return np.concatenate(block_data_list, 0), \
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate

Process finished with exit code 1

**Comment by dlinzhao** [comment]
@PengboLi1998  You can check that the data is loaded correctly.
