### ISSUE TITLE
[ERROR]When Running utils/s3dis_utils/s3dis_gen_h5.py

### ISSUE THREAD

**Issue by Hatsu1314Casper** [dlinzhao/JSNet#22]
**The following error will occur at the beginning of the program:**
/root/autodl-tmp/JSNet/data/indoor3d_ins_seg_hdf5/Area_1_conferenceRoom_1.h5: (80, 4096, 9), (80, 4096), (80, 4096)
Traceback (most recent call last):
  File "utils/s3dis_utils/s3dis_gen_h5.py", line 56, in <module>
    data_dtype, label_dtype)
  File "/root/autodl-tmp/JSNet/utils/data_prep_util.py", line 111, in save_h5ins
    h5_fout = h5py.File(h5_filename)
  File "/root/miniconda3/envs/tf1/lib/python3.6/site-packages/h5py/_hl/files.py", line 427, in __init__
    swmr=swmr)
  File "/root/miniconda3/envs/tf1/lib/python3.6/site-packages/h5py/_hl/files.py", line 190, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 96, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = '/root/autodl-tmp/JSNet/data/indoor3d_ins_seg_hdf5/Area_1_conferenceRoom_1.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

**Error performance:**

1. room_filelist.txt only outputs the conferenceRoom of Aere1
2. missing area_1_conferenceRoom_1.h5 in indoor3d_ins_seg_hdf5

**SOLUTION**
After trying, I found that if I change h5py.file in the function save_h5ins to mode='a', it will run successfully
_data_prep_util.py, line 111_
`h5_fout = h5py.File(h5_filename, mode='a')`

**END**
Hoping that other beginners like me will not be troubled by this error.

**Comment by dlinzhao** [comment]
Using `ln` to create a symbolic link and link to the data, see to readme file.

**Comment by zzzty26** [comment]
> **The following error will occur at the beginning of the program:** /root/autodl-tmp/JSNet/data/indoor3d_ins_seg_hdf5/Area_1_conferenceRoom_1.h5: (80, 4096, 9), (80, 4096), (80, 4096) Traceback (most recent call last): File "utils/s3dis_utils/s3dis_gen_h5.py", line 56, in data_dtype, label_dtype) File "/root/autodl-tmp/JSNet/utils/data_prep_util.py", line 111, in save_h5ins h5_fout = h5py.File(h5_filename) File "/root/miniconda3/envs/tf1/lib/python3.6/site-packages/h5py/_hl/files.py", line 427, in **init** swmr=swmr) File "/root/miniconda3/envs/tf1/lib/python3.6/site-packages/h5py/_hl/files.py", line 190, in make_fid fid = h5f.open(name, flags, fapl=fapl) File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper File "h5py/h5f.pyx", line 96, in h5py.h5f.open OSError: Unable to open file (unable to open file: name = '/root/autodl-tmp/JSNet/data/indoor3d_ins_seg_hdf5/Area_1_conferenceRoom_1.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
> 
> **Error performance:**
> 
> 1. room_filelist.txt only outputs the conferenceRoom of Aere1
> 2. missing area_1_conferenceRoom_1.h5 in indoor3d_ins_seg_hdf5
> 
> **SOLUTION** After trying, I found that if I change h5py.file in the function save_h5ins to mode='a', it will run successfully _data_prep_util.py, line 111_ `h5_fout = h5py.File(h5_filename, mode='a')`
> 
> **END** Hoping that other beginners like me will not be troubled by this error.

Can you leave me a contact number? I have a question for you
